### PR TITLE
git week2 hw step 8

### PR DESCRIPTION
**Pull request by mehmetnuricavdar**

### CODE REVIEW

**Review by marta-ov — CHANGES_REQUESTED** [review]
I think you forgot step 6, which makes step 7 a bit different, so please go back to step 6 and continue from there ;P 
Ping me on slack when you are done please :)

**Comment by mehmetnuricavdar** [comment]
> I think you forgot step 6, which makes step 7 a bit different, so please go back to step 6 and continue from there ;P Ping me on slack when you are done please :)

i did actually and it gave me conflict error and i solved then moved to other steps :)))

**Comment by mehmetnuricavdar** [comment]
closed for doing hw from scratch

**Comment by marta-ov** [comment]
That sounds weird, then there should be two commits in the branch `git-week2` related to this homework, and i only see one: https://github.com/mehmetnuricavdar/hyf-homework/commits/git-week2

Also, there would be a commit with two parents and not just one:
image

Did you maybe forget to push something?

**Pull request closed without merging**
