### PR TITLE
GIT week2 hw features/veggies branch step 5

### PR DESCRIPTION
**Pull request by mehmetnuricavdar**

### CODE REVIEW

**Comment by marta-ov** [comment]
I still don't see the commit from step 6 xD
Did you go to github, branch git-week2, and do the commit in step 6?

**Comment by mehmetnuricavdar** [comment]
> I still don't see the commit from step 6 xD Did you go to github, branch git-week2, and do the commit in step 6?

now you should see i guess

**Comment by marta-ov** [comment]
Yes! Now i see it :)
Now you need to do step 7 again, as in, you need to get git-week2 from github into git-week2 in your computer and then merge it with feature/veggies.

**Comment by marta-ov** [comment]
whhhhyyyyy? why did you merge the PR? :joy:

**Comment by mehmetnuricavdar** [comment]
> whhhhyyyyy? why did you merge the PR? 😂

ahahah you said it merge 😂

**Comment by marta-ov** [comment]
Did you read all the words in the sentence? :stuck_out_tongue_closed_eyes:

**Comment by mehmetnuricavdar** [comment]
i think i read it but let me revert it or making more mess 🤣

**Pull request merged**
