### PR TITLE
Git week1 homework

### PR DESCRIPTION
**Pull request by mehmetnuricavdar**
This is my Git week1 homework

### CODE REVIEW

**Review by marta-ov — CHANGES_REQUESTED** [review]
This is perfect! :D
I have one last task for you, to mimic the process of implementing mentor feedback: can you add one more country name to the file countries.txt, commit, and push please?
And then you'll see that the new commit shows up on this PR automatically :)

Also, the commit messages are very good! But a suggestion for the future is that you can also make them shorter (while keeping them meaningful) by writing, e.g. "Add file countries.txt".

**Comment by marta-ov** [comment]
Exercise 1 is also perfect btw, nothing to do there :)

**Comment by mehmetnuricavdar** [comment]
> This is perfect! :D I have one last task for you, to mimic the process of implementing mentor feedback: can you add one more country name to the file countries.txt, commit, and push please? And then you'll see that the new commit shows up on this PR automatically :)
> 
> Also, the commit messages are very good! But a suggestion for the future is that you can also make them shorter (while keeping them meaningful) by writing, e.g. "Add file countries.txt".

Hi Marta, i guess i did and i see my second request is with first one, this is magical :))))

**Review by marta-ov — APPROVED** [review]
Well done! Thank you :)
You can now merge your PR :)

**Comment by alexchessmaster** [comment]
I liked the name of the last commit. 
Still, sometimes I search "commit naming conventions" on google to recall the naming conventions but so far I just can say perfect!

**Review by alexchessmaster — COMMENTED** [review]
Good job

**Comment by mehmetnuricavdar** [comment]
> Good job

Thank you, i am checking "commit naming conventions" also.

**Pull request merged**
